name: PR test
on:
  push:
    branches:
      - master
  schedule:
      - cron: '*/1 * * * *'

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update Test
        run: |
          echo "Testing PR GH action" >> test.txt

      - name: Issue Pull Request
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[BOT] Conda Lock Update"
          title: "[BOT] Conda Lock Update"
          body: Pull Request created by the ${{ env.GITHUB_WORKFLOW }} workflow.
          branch: bot-conda-lock-update
          labels: bot-conda-lock-update,kokoro:force-run
          delete-branch: true
          signoff: true
